"ENV_NAME": "MPE_simple_tag_v3"
"NUM_ENVS": 8
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2e6
"AGENT_HIDDEN_DIM": 64
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MIXER_EMBEDDING_DIM": 32
"MIXER_HYPERNET_HIDDEN_DIM": 64
"MAX_GRAD_NORM": 25
"TARGET_UPDATE_INTERVAL": 200 
"LR": 0.005
"EPS_ADAM": 1e-2
"WEIGHT_DECAY_ADAM": 0.00001
"GAMMA": 0.9
"DEBUG": False