"NUM_ENVS": 8
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2e6
"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 2.
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MAX_GRAD_NORM": 25
"TARGET_UPDATE_INTERVAL": 200 
"LR": 0.005
"EPS_ADAM": 0.001
"GAMMA": 0.9
"VERBOSE": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 5e4