"LR": 4e-4
"NUM_ENVS": 16 
"NUM_STEPS": 128 # must be 128
"TOTAL_TIMESTEPS": 2e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.01
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_spread_v3"
"SEED": 30
"NUM_SEEDS": 2
"ENV_KWARGS": {}
"ANNEAL_LR": True

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": ""
"PROJECT": "jaxmarl-mpe"