"LR": 4e-3
"NUM_ENVS": 128 # must be a multiple of 8
"NUM_STEPS": 128 # must be 128
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.05
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"ENV_NAME": "HeuristicEnemyMiniSMAC"
"MAP_NAME": "smacv2_5_units"
"SEED": 0
#"NUM_SEEDS": 2
"ENV_KWARGS": 
  "see_enemy_actions": True
  "walls_cause_death": True
  "attack_mode": "closest"
"ANNEAL_LR": True

"DISABLE_JIT": False
"WANDB_MODE": "online"
"ENTITY": "amacrutherford"
"PROJECT": "smax-rnn"
"DEVICE": 0