"LR": 6e-4
"NUM_ENVS": 32
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 5e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.98
"CLIP_EPS": 0.05
"ENT_COEF": 0.1
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.1
"ACTIVATION": "relu"
"ENV_NAME": "overcooked"
"REW_SHAPING_HORIZON": 2.5e6
"ENV_KWARGS": 
  "layout" : "cramped_room"
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 3
"TUNE": False

# WandB Params
"ENTITY": "mttga"
"PROJECT": "jaxmarl-overcooked"
"WANDB_MODE" : "online"
