"ENV_NAME": "MPE_simple_spread_v3"
"NUM_ENVS": 8
"BUFFER_SIZE": 5000  # int 
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2e6 
"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 2.0
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 1e5
"MAX_GRAD_NORM": 25
"TARGET_UPDATE_INTERVAL": 200 
"LR": 5e-3
"EPS_ADAM": 1e-3
"GAMMA": 0.99
"DEBUG": False
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 5e4
"VERBOSE": False
"SEED": 30
"NUM_SEEDS": 10

"ENTITY": "amacrutherford"
"PROJECT": "mpe-smax"
"WANDB_MODE": "online"