"ENV_NAME": "MPE_simple_adversary_v3"
"NUM_ENVS": 8
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2.0e6
"AGENT_HIDDEN_DIM": 64
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200 
"LR": 0.005
"GAMMA": 0.99
"DEBUG": False
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 5.0e4
"SEED": 30
"NUM_SEEDS": 10

"ENTITY": "amacrutherford"
"PROJECT": "mpe-smax"
"WANDB_MODE": "online"