"ENV_NAME": "MPE_simple_spread_v3"
"NUM_ENVS": 8
"BUFFER_SIZE": 5e3
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2e6 
"AGENT_HIDDEN_DIM": 64
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 1e5
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200 
"LR": 5e-3
"GAMMA": 0.99
"DEBUG": False
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 5e4