"NUM_ENVS": 8
"NUM_STEPS": 32
"BUFFER_SIZE": 1e6
"BUFFER_BATCH_SIZE": 256
"TOTAL_TIMESTEPS": 2e6
"HIDDEN_SIZE": 64
"N_LAYERS": 2
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.5
"MAX_GRAD_NORM": 1
"TARGET_UPDATE_INTERVAL": 200
"TAU": 1.
"NUM_MINI_EPOCHS": 1
"LR": 0.0005
"LEARNING_STARTS": 10000
"LR_LINEAR_DECAY": True
"LOSS_TYPE": "iql" # iql, vdn or qmix
"GAMMA": 0.99
"WANDB_LOG_DURING_TRAINING": True
"NUM_TEST_EPISODES": 4
"TEST_POLICY_UPDATE_INTERVAL": 1000
"ALG_NAME": "iql_ff"