"NUM_ENVS": 32
"NUM_STEPS": 32
"TOTAL_TIMESTEPS": 5e6
"HIDDEN_SIZE": 64
"NORM_TYPE": "layer_norm"
"NORM_INPUT": False
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.3
"MAX_GRAD_NORM": 10
"CLIP_EPS": 
"NUM_MINIBATCHES": 16
"NUM_EPOCHS": 4
"LR": 0.0001
"LR_LINEAR_DECAY": True
"LAMBDA": 0.8
"GAMMA": 0.99
"WANDB_LOG_DURING_TRAINING": True
"PREPROCESS_OBS": False
"TEST_INTERVAL": 100
"NUM_TEST_STEPS": 400
"NUM_TEST_EPISODES": 16
"ALG_NAME": "pqn_vdn_cnn"

"REW_SHAPING_HORIZON": 2.5e6