"NUM_ENVS": 64
"NUM_STEPS": 16
"TOTAL_TIMESTEPS": 5e6
"HIDDEN_SIZE": 256
"NORM_TYPE": "layer_norm"
"NORM_INPUT": False
"EPS_START": 1.0
"EPS_FINISH": 0.2
"EPS_DECAY": 0.2
"MAX_GRAD_NORM": 10
"NUM_MINIBATCHES": 16
"NUM_EPOCHS": 5
"LR": 0.000075
"LR_LINEAR_DECAY": True
"LAMBDA": 0.3
"GAMMA": 0.99

"REW_SHAPING_HORIZON": 2.5e6
"REW_SCALE": 1.

"WANDB_LOG_DURING_TRAINING": True
"PREPROCESS_OBS": False
"TEST_INTERVAL": 10
"NUM_TEST_STEPS": 400
"NUM_TEST_EPISODES": 512
"ALG_NAME": "pqn_machecazz"

"SAVE_DIR": "/gpfs/scratch/bsc28/bsc028921/jax_23.10-py3/home/JaxMARL/saved_metrics_oc/rew_0.5"

