"NUM_ENVS": 32
"NUM_STEPS": 16
"TOTAL_TIMESTEPS": 2e6
"HIDDEN_SIZE": 64
"N_LAYERS": 2
"NORM_TYPE": "layer_norm"
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.1
"MAX_GRAD_NORM": 25
"NUM_MINIBATCHES": 4
"NUM_EPOCHS": 4
"LR": 0.005
"LR_LINEAR_DECAY": True
"GAMMA": 0.9
"WANDB_LOG_DURING_TRAINING": True
"TEST_INTERVAL": 100
"NUM_TEST_STEPS": 30
"NUM_TEST_EPISODES": 8
"ALG_NAME": "pqn_vdn_ff"