"NUM_ENVS": 512
"MEMORY_WINDOW": 128
"NUM_STEPS": 16
"TOTAL_TIMESTEPS": 1e7
"HIDDEN_SIZE": 512
"N_LAYERS": 2
"NORM_TYPE": "layer_norm"
"EPS_START": 0.1
"EPS_FINISH": 0.01
"EPS_DECAY": 0.1
"MAX_GRAD_NORM": 10
"NUM_MINIBATCHES": 4
"NUM_EPOCHS": 4
"LR": 0.00005
"LR_LINEAR_DECAY": True
"GAMMA": 0.99
"WANDB_LOG_DURING_TRAINING": True
"PREPROCESS_OBS": True
"TEST_INTERVAL": 100
"NUM_TEST_STEPS": 128
"NUM_TEST_EPISODES": 16
"ALG_NAME": "pqn_vdn_rnn"