"NUM_ENVS": 64
"MEMORY_WINDOW": 0
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 1e7
"HIDDEN_SIZE": 512
"N_LAYERS": 2
"NORM_TYPE": "layer_norm"
"EPS_START": 1.
"EPS_FINISH": 0.001
"EPS_DECAY": 0.1
"MAX_GRAD_NORM": 1
"NUM_MINIBATCHES": 16
"NUM_EPOCHS": 4
"LR": 0.0005
"LR_LINEAR_DECAY": True
"GAMMA": 0.99
"LAMBDA": 0.9
"REW_SCALING": 10

"WANDB_LOG_DURING_TRAINING": True
"PREPROCESS_OBS": True
"TEST_INTERVAL": 10
"NUM_TEST_STEPS": 128
"NUM_TEST_EPISODES": 16
"ALG_NAME": "5m_lr0005"