"NUM_ENVS": 1024
"NUM_STEPS": 1
"TOTAL_TIMESTEPS": 1e10
"HIDDEN_SIZE": 512
"N_LAYERS": 3
"NORM_TYPE": "layer_norm"
"DUELING": True
"EPS_START": 0.01
"EPS_FINISH": 0.001
"EPS_DECAY": 0.1
"MAX_GRAD_NORM": 0.5
"NUM_MINIBATCHES": 1
"NUM_EPOCHS": 1
"LR": 3e-4
"LR_LINEAR_DECAY": False
"GAMMA": 0.99
"WANDB_LOG_DURING_TRAINING": True
"PREPROCESS_OBS": False
"TEST_INTERVAL": 10000
"NUM_TEST_STEPS": 100
"NUM_TEST_EPISODES": 100000
"ALG_NAME": "pqn_vdn_ff_100k_tests"