"NUM_ENVS": 32
"NUM_STEPS": 1
"BUFFER_SIZE": 1e5
"BUFFER_BATCH_SIZE": 128
"TOTAL_TIMESTEPS": 5e6
"HIDDEN_SIZE": 64
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.1
"LEARNING_STARTS": 1e3
"MAX_GRAD_NORM": 1
"TARGET_UPDATE_INTERVAL": 50
"NUM_MINI_EPOCHS": 4
"LOSS_TYPE": "vdn"
"LR": 0.0001
"LR_LINEAR_DECAY": True
"GAMMA": 0.99
"TAU": 1.
"REW_SHAPING_HORIZON": 2.5e6
"WANDB_LOG_DURING_TRAINING": True
"TEST_DURING_TRAINING": True
"TEST_ENVS": 32
"TEST_POLICY_UPDATE_INTERVAL": 5000
"ALG_NAME": "vdn"