"NUM_ENVS": 8
"NUM_STEPS": 25
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2e6
"HIDDEN_SIZE": 64
"MIXER_EMBEDDING_DIM": 32 # just for qmix
"MIXER_HYPERNET_HIDDEN_DIM": 128 # just for qmix
"MIXER_INIT_SCALE": 0.001 # just for qmix
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.1 # percentage of updates
"MAX_GRAD_NORM": 25
"TARGET_UPDATE_INTERVAL": 200
"TAU": 1.
"NUM_MINI_EPOCHS": 1
"LR": 0.005
"LEARNING_STARTS": 10000 # timesteps
"LR_LINEAR_DECAY": True
"GAMMA": 0.9
"WANDB_LOG_DURING_TRAINING": True
"TEST_INTERVAL": 10 # updates
"TEST_ENVS": 32
"NUM_TEST_STEPS": 128
"ALG_NAME": "rnn"