"NUM_ENVS": 8
"NUM_STEPS": 128
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 20000000
"AGENT_HIDDEN_DIM": 32
"AGENT_INIT_SCALE": 1.
"AGENT_TRANSF_NUM_LAYERS": 2
"AGENT_TRANSF_NUM_HEADS": 8
"AGENT_TRANSF_DIM_FF": 128
"MIXER_EMBEDDING_DIM": 32
"MIXER_HYPERNET_HIDDEN_DIM": 64
"MIXER_INIT_SCALE": 0.00001
"PARAMETERS_SHARING": True
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MAX_GRAD_NORM": 1.
"TARGET_UPDATE_INTERVAL": 200 
"LR": 0.005
"LR_LINEAR_DECAY": False
"LR_COSINE_WARMUP": True
"LR_WARMUP": 10
"EPS_ADAM": 0.001
"TD_LAMBDA_LOSS": True
"TD_LAMBDA": 0.6
"GAMMA": 0.99
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000