"NUM_ENVS": 8
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 2050000
"AGENT_INIT_SCALE": 2.
"AGENT_HIDDEN_DIM": 32
"AGENT_TRANSF_NUM_LAYERS": 2
"AGENT_TRANSF_NUM_HEADS": 4
"AGENT_TRANSF_DIM_FF": 128
"PARAMETERS_SHARING": True
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MIXER_INIT_SCALE": 0.0001
"MIXER_TRANSF_NUM_LAYERS": 2
"MIXER_TRANSF_NUM_HEADS": 4
"MIXER_TRANSF_DIM_FF": 128
"MAX_GRAD_NORM": 100
"TARGET_UPDATE_INTERVAL": 200
"LR": 0.0001
"LR_LINEAR_DECAY": False
"EPS_ADAM": 0.001
"WEIGHT_DECAY_ADAM": 0.00001
"TD_LAMBDA_LOSS": True
"TD_LAMBDA": 0.6
"GAMMA": 0.9
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000