"NUM_ENVS": 32
"NUM_STEPS": 16
"BUFFER_SIZE": 1e6
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 1e7
"HIDDEN_SIZE": 64
"N_LAYERS": 2
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.1
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200
"TAU": 1.
"NUM_MINI_EPOCHS": 1
"LR": 0.001
"LEARNING_STARTS": 10000
"LR_LINEAR_DECAY": False
"LOSS_TYPE": "vdn" # iql, vdn or qmix
"GAMMA": 0.99
"WANDB_LOG_DURING_TRAINING": True
"NUM_TEST_EPISODES": 4
"TEST_POLICY_UPDATE_INTERVAL": 200
"ALG_NAME": "vdn_ff"