"NUM_ENVS": 32
"NUM_STEPS": 128
"BUFFER_SIZE": 5000
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 1e7
"HIDDEN_SIZE": 256
"EPS_START": 1.0
"EPS_FINISH": 0.05
"EPS_DECAY": 0.05
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200
"TAU": 1.
"NUM_MINI_EPOCHS": 1
"LR": 0.001
"LEARNING_STARTS": 10000 # timesteps
"LR_LINEAR_DECAY": False
"GAMMA": 0.99
"WANDB_LOG_DURING_TRAINING": True
"TEST_INTERVAL": 100 # updates
"TEST_ENVS": 8
"NUM_TEST_STEPS": 128
"ALG_NAME": "vdn_rnn"